### ISSUE TITLE
Please create .zip release for Notepad++ Plugin Manager

### ISSUE THREAD

**Issue by bruderstein** [larryb82/npp-regexhelper#1]
Notepad++ Plugin Manager can only really download .zip files. Can you make a .zip release, then we can add it properly - got to remove it for now. 

Thanks!

**Comment by chcg** [comment]
@larryb82 added data for 0.2.3 to https://npppm.bruderste.in/plugins/view/regex-helper

**Comment by chcg** [comment]
@larryb82  Do you plan a 64bit version of your plugin? Would be added to PM here https://github.com/bruderstein/npp-plugins-x64/commits/master
